# Generated by Django 4.2 on 2026-03-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_populate_habilidades'),
    ]

    operations = [
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id_freelancer', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=100, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('data_nasc', models.DateField(blank=True, null=True)),
                ('num_tel', models.CharField(blank=True, max_length=20)),
                ('num_cel', models.CharField(blank=True, max_length=20)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('habilidades', models.ManyToManyField(blank=True, related_name='freelancers', to='usuarios.habilidade')),
            ],
            options={
                'verbose_name': 'Freelancer',
                'verbose_name_plural': 'Freelancers',
                'db_table': 'tab_freelancer',
                'ordering': ['nome', 'sobrenome'],
            },
        ),
    ]
