services:
  - type: web
    runtime: python
    name: workflow-python-api
    rootDir: backend
    plan: free
    buildCommand: pip install -r requirements.txt
    preDeployCommand: python manage.py migrate
    startCommand: python manage.py migrate && python povoar_dados_demo.py && python -m gunicorn workflow.wsgi:application
    healthCheckPath: /api/categorias/
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.10
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: FRONTEND_BASE_URL
        value: https://workflow-python.vercel.app
      - key: DEFAULT_FROM_EMAIL
        value: no-reply@workflow.local
      - key: EMAIL_BACKEND
        value: django.core.mail.backends.console.EmailBackend
