# Generated by Django 4.2 on 2026-03-25 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemDeServico',
            fields=[
                ('id_os', models.AutoField(primary_key=True, serialize=False)),
                ('descricao_servico', models.TextField()),
                ('valor_estimado_minimo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_estimado_maximo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='aberta', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('contratante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_contratadas', to='usuarios.usuario')),
                ('freelancer_selecionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_selecionadas', to='usuarios.usuario')),
                ('freelancers_candidatos', models.ManyToManyField(blank=True, related_name='ordens_candidatas', to='usuarios.usuario')),
                ('habilidades_necessarias', models.ManyToManyField(blank=True, related_name='ordens', to='usuarios.habilidade')),
            ],
            options={
                'db_table': 'tab_ordem_servico',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
