# Generated by Django 4.2 on 2026-04-02 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemdeservico',
            name='status',
            field=models.CharField(choices=[('em_aberto', 'Em Aberto'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='em_aberto', max_length=20),
        ),
    ]
