# Generated by Django 4.2 on 2026-04-07 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0004_add_imagem_field'),
    ]

    operations = [
    ]
