# Generated by Django 4.2 on 2026-04-09 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0005_register_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemdeservico',
            name='habilidades_necessarias',
        ),
    ]
