# Generated by Django 4.2 on 2026-04-09 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_categoria_notificacao_remove_usuario_habilidades_and_more'),
        ('ordens', '0006_remove_ordemdeservico_habilidades_necessarias'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemdeservico',
            name='categorias_necessarias',
            field=models.ManyToManyField(blank=True, related_name='ordens', to='usuarios.categoria'),
        ),
    ]
