# Generated by Django 6.0.4 on 2026-05-01 19:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def normalize_statuses(apps, schema_editor):
    OrdemDeServico = apps.get_model('ordens', 'OrdemDeServico')
    OrdemDeServico.objects.filter(status='concluido').update(status='finalizado')
    OrdemDeServico.objects.filter(status='concluida').update(status='finalizado')
    OrdemDeServico.objects.filter(status='em_andamento').update(status='em_execucao')
    OrdemDeServico.objects.filter(status='em_aberto').update(status='aberta')


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0008_chat_conversas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(normalize_statuses, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='ordemdeservico',
            name='status',
            field=models.CharField(choices=[('aberta', 'Aberta'), ('em_execucao', 'Em execucao'), ('finalizado', 'Finalizado')], default='aberta', max_length=20),
        ),
        migrations.CreateModel(
            name='AvaliacaoOrdem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('avaliador_tipo', models.CharField(choices=[('contratante', 'Contratante'), ('freelancer', 'Freelancer')], max_length=20)),
                ('nota_profissional', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('nota_plataforma', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('avaliado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_recebidas', to=settings.AUTH_USER_MODEL)),
                ('avaliador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_feitas', to=settings.AUTH_USER_MODEL)),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='ordens.ordemdeservico')),
            ],
            options={
                'db_table': 'tab_avaliacao_ordem',
                'ordering': ['-data_criacao'],
                'constraints': [models.UniqueConstraint(fields=('ordem_servico', 'avaliador'), name='uniq_avaliacao_ordem_avaliador')],
            },
        ),
    ]
