# Generated by Django 4.2 on 2026-04-05 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0002_alter_ordemdeservico_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemdeservico',
            name='status',
            field=models.CharField(choices=[('aberta', 'Aberta'), ('em_execucao', 'Em Execução'), ('concluido', 'Concluído')], default='aberta', max_length=20),
        ),
    ]
