# Generated by Django 4.2 on 2026-03-25 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Habilidade',
                'verbose_name_plural': 'Habilidades',
                'db_table': 'tab_habilidade',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=100, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('nome', models.CharField(max_length=100)),
                ('sobre_nome', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('num_tel', models.CharField(blank=True, max_length=20)),
                ('num_cel', models.CharField(blank=True, max_length=20)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('freelancer', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('habilidades', models.ManyToManyField(blank=True, related_name='usuarios', to='usuarios.habilidade')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'tab_usuario',
                'ordering': ['nome', 'sobre_nome'],
            },
        ),
    ]
