# Generated by Django 6.0.4 on 2026-04-21 02:45

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usuarios', '0008_categoria_notificacao_remove_usuario_habilidades_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('login'), name='uniq_usuario_login_ci'),
        ),
    ]
