# Generated by Django 4.2 on 2026-04-23 00:00

from django.db import migrations, models
import django.db.models.deletion
import usuarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_usuario_uniq_usuario_login_ci'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnuncioServico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_profissional', models.CharField(max_length=120)),
                ('descricao', models.TextField()),
                ('portfolio_url', models.URLField(blank=True)),
                ('portfolio_arquivo', models.FileField(blank=True, null=True, upload_to='anuncios/portfolio/', validators=[usuarios.models.validate_portfolio_file_size])),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('freelancer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anuncio_servico', to='usuarios.usuario')),
                ('habilidades', models.ManyToManyField(blank=True, related_name='anuncios_servico', to='usuarios.categoria')),
            ],
            options={
                'verbose_name': 'Anuncio de Servico',
                'verbose_name_plural': 'Anuncios de Servico',
                'db_table': 'tab_anuncio_servico',
                'ordering': ['-data_atualizacao', '-data_criacao'],
            },
        ),
    ]
