# Generated by Django 4.2 on 2026-04-23 00:00

from django.db import migrations, models
import usuarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_anuncioservico'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncioservico',
            name='foto_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='anuncios/avatar/', validators=[usuarios.models.validate_avatar_file_size]),
        ),
    ]
