# Generated by Django 6.0.4 on 2026-05-01 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_remove_unwanted_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['nome', 'sobre_nome'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
