# Generated by Django 6.0.4 on 2026-05-01 22:43

import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_usuario_avaliacao_media_usuario_total_avaliacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/perfil/', validators=[usuarios.models.validate_avatar_file_size]),
        ),
    ]
